version: '2'
services:
  jenkins:
    image: 'bitnami/jenkins:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    environment:
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=admin
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
volumes:
  jenkins_data:
    driver: local
