---
- name: yum install required packages
  yum:
    name:
      - epel-release
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - bash-completion
    state: present

- name: add repository via yum-config-manager
  command: 'yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo'

- name: yum install docker-ce && docker-compose
  yum:
    name: 
      - docker-ce
      - docker-compose
    state: present

- name: docker start
  service:
    name: docker
    state: started
    enabled: yes

- name: copy yml files
  copy:
    src: ./
    dest: /docker-compose
