version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:5.0.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
  elasticsearch:
    image: elasticsearch
